// Objective-C API for talking to github.com/incipher/crypto Go package.
//   gobind -lang=objc github.com/incipher/crypto
//
// File is generated by gobind. Do not edit.

#ifndef __Crypto_H__
#define __Crypto_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


FOUNDATION_EXPORT NSString* _Nonnull CryptoScrypt(NSString* _Nullable password, NSString* _Nullable salt, long workFactor, long blockSize, long parallelizationFactor, long derivedKeyLength, NSString* _Nullable derivedKeyEncoding);

#endif
